docs/developer.md
=> add developer contribution docs

demo/basic/test.sh
=> chore(deploy): add storage provisioner's deploy artifacts to demo

controller/blockdevice/reconciler.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, deploy/operator.yaml, util/metac/hook.go
=> chore(debug): add extra logs to facilitate debugging

controller/cstorclusterconfig/reconciler.go
This commit should fix below error:
```yaml
status:
conditions:
- lastObservedTime: "2019-12-17 05:14:48.534533"
reason: 'Can''t unmarshal CStorClusterPlan: Object ''Kind'' is missing in ''{"metadata":{"creationTimestamp":null},"spec":{"nodes":[{"name":"gke-amitd-dao-d-default-pool-fcc50975-blz8","uid":"bb3c94a2-1b11-11ea-a90b-42010a800016"},{"name":"gke-amitd-dao-d-default-pool-fcc50975-fvsb","uid":"ba217ce0-1b11-11ea-a90b-42010a800016"},{"name":"gke-amitd-dao-d-default-pool-fcc50975-wt3x","uid":"bb3318c7-1b11-11ea-a90b-42010a800016"}]},"status":{"phase":"","conditions":null}}'''
status: "True"
type: CStorClusterConfigReconcileError
phase: Error
```
=> fix(nil): fix code to avoid sending nil CStorClusterPlan

config/metac.yaml
=> fix(config): fix invalid indentation in config yaml

controller/blockdevice/reconciler.go, util/metac/hook.go
The commit should fix the case where duplicate blockdevices were sent during association.
=> fix(blockdevice): association logic with storage

controller/blockdevice/reconciler.go
This logic tries to solve the problem of data getting set into blockdevice's annotations in a recursive manner. This in turn leads to setting of wrong annotations.
This also indicates a bug in metac while setting annotations during update via GenericController.
=> fix(workaround): return only the associated blockdevice

TODO, docs/design.md
=> chore(docs): update TODO & design docs

README.md, demo/basic/basic.yaml, deploy/namespace.yaml, deploy/operator.yaml, deploy/rbac.yaml
This commit updates the README with the basic yaml file used to run the demo.
=> chore(docs): update README with basic yaml

README.md
=> docs(README): update readme with steps to run cstorpoolauto

Dockerfile, TODO, go.mod, go.sum
=> chore(dependency): update metac to current master branch

controller/blockdevice/reconciler.go
This commit sets resync & skip reconcile flags to trigger a resync if blockdevice to storage association did not happen. Both these flags should reduce the overall time required to bring up the
CStorPoolCluster aka CSPC.
=> fix(resync): resync & skip reconcile if association did not happen

Dockerfile, controller/blockdevice/reconciler.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, controller/cstorpoolcluster/reconciler_test.go, unstruct/condition.go, unstruct/condition_test.go, unstruct/iterator.go, unstruct/iterator_test.go, unstruct/unstruct.go, unstruct/unstruct_test.go, unstruct/util.go, unstruct/util_test.go
=> chore(rename): rename k8s to unstruct package

controller/cstorpoolcluster/reconciler.go, controller/cstorpoolcluster/reconciler_test.go
=> fix(cspc): fix nil pointer during cspc node to blockdevice mapping

controller/cstorpoolcluster/reconciler.go, controller/cstorpoolcluster/reconciler_test.go
This commit has also additional unit tests that confirms this bug fix.
=> fix(nil map): fix nil map assignment in cspc controller

README.md
=> chore(readme): update readme with latest specs

go.mod, go.sum
=> chore(metac): update to latest metac version

types/raidgroupconfig.go, types/raidgroupconfig_test.go, types/recommendationrequest.go
Add validation methods for RaidGroupConfig
=> feat(recommendation): Add methods and validation for raid group config

.github/workflows/build-image.yml, types/raidgroupconfig.go, types/raidgroupconfig_test.go, util/blockdevice/util.go
This PR contains - 
Some refactoring of previous code.
More UT.
Address previous comments.
=> refactor(recommendation): Refactor, address previous review comments and add more UT.

pkg/recommendation/device.go
This PR updates the metadata of response from the request.
Signed-off-by: Sumit Lalwani <sumit.lalwani97@gmail.com>
=> fix(recommendation): update metadata in device recommendation

config/metac.yaml, controller/localdevice/reconciler.go, controller/localdevice/reconciler_test.go, go.mod, go.sum, types/annotations.go, types/cstorclusterconfig.go, unstruct/selector_test.go, util/cstorclusterconfig/helper.go, util/cstorclusterconfig/helper_test.go
This commit closes following issues:
- https://github.com/mayadata-io/cstorpoolauto/issues/106
- https://github.com/mayadata-io/cstorpoolauto/issues/104
- https://github.com/mayadata-io/cstorpoolauto/issues/103
- https://github.com/mayadata-io/cstorpoolauto/issues/102
=> fix(localdevice): fix various bugs related to localdevice

go.mod, pkg/recommendation/capacity.go, pkg/recommendation/device.go, util/blockdevice/topology.go, util/blockdevice/util.go
This PR contains -
1. Update the JSON path to get different properties of the block device to be sync with NDM.
2. Remove TODO and add warning logs.
=> chore(block-device-util): update json path for block device

Jenkinsfile
Signed-off-by: atulabhi <atul.abhishek@mayadata.io>
=> upudate build tag to semver from git sha

demo/local-device/README.md, demo/local-device/readme.md
add steps to create cStor pool using local bd
=> chore(doc): add steps to create cstor pool using local devices
