mayadata-io/cstorpoolauto

cmd/main.go, controller/clusterconfig/node/node.go, controller/clusterconfig/reconciler/reconciler.go, types/conditions.go, types/cstorclusterconfig.go, types/cstorclusterconfig_plan.go
This commit adds a new custom resource known as CStorClusterConfigPlan. This removes the earlier logic of remembering desired nodes from CStorClusterConfig.status.
This resource will provide the nodes to be used to form CStorPoolCluster.
=> feat(controller): add CStorClusterConfigPlan resource

controller/blockdevice/reconciler.go, controller/poolcluster/reconciler.go, k8s/k8s.go, types/status.go
This commit includes logic that watches CStorClusterPlan resource and reconciles CStorPoolCluster (aka CSPC). This controller logic makes use of other resources to achieve the desired state for CStorPoolCluster.
The resources that are used to get CStorPoolCluster into its desired state are:
- CStorClusterPlan (watch)
- CStorClusterConfig
- CStorClusterStorageSet
- BlockDevice
=> feat(controller): add controller to apply CStorPoolCluster

controller/cstorclusterconfig/reconciler.go, demo/basic/cspc-operator.yaml, demo/basic/openebs-operator-1.5.0.yaml, demo/basic/storage_crd.yaml, demo/basic/storage_deployment.yaml, demo/basic/storage_rbac.yaml, demo/basic/test.sh, deploy/rbac.yaml, go.mod, go.sum
This commit throws error if either hook request or hook response are nil. These objects are expected to be instantiated by metac. Reconciliation will not work as expected if any one or both of them are nil.
This commit also has additional scripts, artifacts required to deploy or delete the entire cstorpoolauto setup.
=> fix(reconciler): throw errors for nil hook request or response

controller/blockdevice/reconciler.go, k8s/k8s.go, types/status.go
This commit should fix the issue of unmarshalling objects when status.conditions made use of lastObservedTime in string format. 
This should also fix the issue of unable to merge status conditions since unstructured instances from kubernetes always comes up as map[string]interface{}.
=> fix(status): use map[string]interface{} for status conditions

controller/blockdevice/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, k8s/k8s.go, types/cstorclusterconfig.go, types/cstorclusterplan.go, types/cstorclusterstorageset.go, types/status.go
This commit changes the datatype of time to string format to avoid unmarshal errors. We might want to revist the exact time format based on production needs.
In addition, this change has the fixes to throw error if either hook request or hook response is nil.
=> fix(time): set metav1.Time to string format

controller/blockdevice/reconciler.go, controller/cstorclusterconfig/node.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, demo/basic/basic.yaml, demo/basic/gpd_sc.yaml, demo/basic/test.sh, k8s/k8s.go, types/gvk.go
This commit adds kind and other required properties to any instance that gets created via this operator.
In addition, kind, group and version are moved to types package. Finally, verbose error logging is enabled that should print the stack trace in the logs.
=> fix(reconcile): add kind when creating desired instances

controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, k8s/k8s.go
This commit uses apimachinery's json package instead of default json package. This should ensure unstructured instances are unmarshaled properly.
In addition, this commit fixes the logic to merge status conditions when status itself is nil.
=> fix(json): use apimachinery json package

controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go
This commit makes use of reference instead of pointer to unmarshal any object. This should fix similar errors like following:
json: Unmarshal(nil *types.CStorClusterPlan)
=> fix(unmarshal): use reference instead of pointer

config/metac.yaml
This commit sets updateAny to true for specific metac controllers based on the controller's reconciliation logic.
=> fix(config): set updateAny tunable in the config file

config/metac.yaml
This commit sets update stratgey to 'InPlace' against resources that controllers want to update. InPlace implies the same resource instance gets updated.
NOTE: Earlier this was not set that in turn defaulted the update strategy to 'OnDelete' which was not the desired behaviour.
=> fix(config): set updateStrategy to InPlace against desired resources

controller/blockdevice/reconciler.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go
This commit eliminates all the hot loop code paths from reconciler logic. Current logic was setting status conditions against the watched resource of a controller. However, same watch was used by
multiple controllers which led to a scenario of failed updates experienced at one reconciler as this watch was already updated during this reconcile period by some other reconciler.
The logic of setting status seemed to create this hot loop path. They have been commented as of now. We need to come up with a better plan to manage status & their conditions.
=> fix(hot loop): eliminate hot loop code from reconciler logic

TODO, config/metac.yaml, controller/cstorclusterplan/reconciler.go
This commit will fix sending of empty CStorClusterStorageSet from reconciler.
In addition, various TODO items have been added w.r.t refactoring of some reconcilers to eliminate hot loop paths. The suggested plan will be to have a dedicated Defaulting reconciler that sets the defaults against CStorClusterConfig instance.
=> fix(empty): fix sending empty CStorClusterStorageSet

controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go
This commit provides the right way to set Kind & APIVersion in unstructured instances. This should fix sending of nil kind and nil apiversion in hook responses.
=> fix(nil kind): add the right way to set Kind and APIVersion

config/metac.yaml, controller/blockdevice/reconciler.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go
This commit should fix missing annotations from the custom resources. This logic has used unstructured's own method to set annotations.
In addition, there are changes to config file that allows InPlace updates to resources that form the desired state.
=> fix(annotations): use right methods to set annotations

controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go
This change adds the missing reconciliation w.r.t disk details against the CStorClusterStorageSet resources. In addition this commits uses of resource.Quantity in string format to avoid panic as seen below:
```
E1218 06:27:23.621706       1 runtime.go:78] Observed a panic:
&errors.errorString{s:"cannot deep copy resource.Quantity"}
(cannot deep copy resource.Quantity)
goroutine 288 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x12d0a80, 0xc00024db00)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191006235458-f9f2f3f8ab02
/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191006235458-f9f2f3f8ab02
/pkg/util/runtime/runtime.go:48 +0x82
panic(0x12d0a80, 0xc00024db00) …
```
=> fix(panic): use resource.Quanity in string format

controller/cstorclusterplan/reconciler.go
This commit should fixe following panic:
```
E1218 08:05:03.754529       1 runtime.go:78] Observed a panic:
&errors.errorString{s:"cannot deep copy map[string]string"}
(cannot deep copy map[string]string)
goroutine 271 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191006235458-f9f2f3f8ab02
/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191006235458-f9f2f3f8ab02
/pkg/util/runtime/runtime.go:48 +0x82
panic
/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue
/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191006235458-f9f2f3f8ab02
/pkg/runtime/converter.go:474 +0x572 …
```
=> fix(panic): use map[string]interface{} for all unstructured fields

TODO, controller/cstorclusterstorageset/reconciler.go, types/annotations.go
This commit sets storage provisioner based annotations to let storage provisioner to kick in.
Following annotations are used:
```
storageprovisioner.dao.mayadata.io/csi-attacher-name
storageprovisioner.dao.mayadata.io/storageclass-name
```
=> fix(annotations): set storage provisioner annotations

controller/blockdevice/reconciler.go, util/string/string.go
This commit fixes the logic to associate a blockdevice with corresponding storage via annotations.
In addition, the reconcile logic returns un-matched blockdevices to make the reconcile logic idempotent.
=> fix(association): fix blockdevice association with storage

controller/blockdevice/reconciler.go, util/string/string.go
This commit should fix the case where blockdevices were filled up with old & new annotations. With this change the reconcile code needs to bother about the desired annotations & leave the rest to metac that will in turn merge these desired annotations with old annotations if any.
NOTE: This merge logic holds good for any resource specifications as well.
=> fix(annotations): sync only required annotations

controller/blockdevice/reconciler.go
This commit should fix the case when new annotations that are added to the desired state are not getting reflected. It tries to merge the new annotations with existing ones versus earlier way of sending a new annotations instance altogether.
=> fix(annotations): fix missing annotations

controller/blockdevice/reconciler.go, controller/cstorpoolcluster/reconciler.go, deploy/operator.yaml
This commit is a workaround due to a bug in metac. This modified logic moves away from blockdevice annotations & uses labels in its place.
**_NOTE:_**
Metac is not merging the annotations properly when reconciling a resource to its desired state. This happens in GenericController with updateAny set to true and the resource updateStratgey being
InPlace. In addition, it happens when some annotation is modified in the targeted resource with above update tunables.
=> fix(annotations): move to labels from annotations

TODO, controller/cstorclusterplan/reconciler.go, types/gvk.go
This commit fixes the node replacement logic while reconciling CStorClusterPlan resource.
In addition create & update based reconciliations are now idempotent. In other words, single structure is used to represent create as well as update of CStorClusterStorageSet.
=> fix(CStorClusterStorageSet): fix node replacement logic

TODO, controller/cstorclusterstorageset/reconciler.go
This commit makes CStorClusterStorageSet reconciliation idempotent. In other words both create as well update of CStorClusterStorageSet returns same Storage(s) structures.
=> refactor(CStorClusterStorageSet): idempotent reconcile logic

TODO, controller/cstorclusterconfig/reconciler.go
This commit validates the disk count per pool instance based on the specified RAID group type.
=> validate(diskcount): validate disk count w.r.t. RAID group

TODO, controller/cstorclusterconfig/reconciler.go
This commit makes use of a single method to provide the desired state to create or update of CStorClusterPlan resource.
=> refactor(CStorClusterConfig): idempotent create & update reconciliations

TODO, controller/blockdevice/reconciler.go
This commit makes use of idempotent reconcile logic to associate blockdevice with CStorClusterStorageSet and CStorClusterPlan resources.
=> refactor(blockdevice): idempotent reconciliation of blockdevices

k8s/verify.go, k8s/verify_test.go
This commit moves away from use of GetLabels & GetAnnotations methods of unstructured instance and uses core methods to get the values. This has been done to avoid swallowing of errors if any. Unit tests has been added to test this change.
=> refactor(util): update util functions to handle errors

controller/cstorclusterconfig/node.go, controller/cstorclusterconfig/node_test.go
This commit fixes the sorting of nodes by creation timestamp. In addition, this has relevant unit tests to verify this change.
=> fix(node): fix node sort by creation time logic

TODO, controller/cstorpoolcluster/reconciler.go, controller/cstorpoolcluster/reconciler_test.go
This commit fixes the condition that skips reconciliation when desired disk count is less than observed disk count. Logic now allows reconciliation when desired disk count >= observed disk count. In addition, several Unit Tests are added to verify this behaviour.
=> fix(ready conds): fix node disk ready conditions

controller/cstorpoolcluster/reconciler.go, types/status.go
This commit fixes the filtering logic of block devices in the controller that deals with applying CStorPoolCluster. It now filters the devices if claim state is either Claimed or Unclaimed. It further filters the devices which are in Active state.
=> fix(blockdevice): filter blockdevices that are Active

controller/cstorpoolcluster/reconciler.go
Earlier commit introduced a bug where selection of blockdevice logic was set against StorageSet instead of blockdevice. 
A long term approach will be to make use of selection & pick utility functions with better code coverage.
=> fix(blockdevice): fix selection of blockdevice

TODO, controller/cstorclusterconfig/node.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterconfig/reconciler_test.go, k8s/util.go, k8s/util_test.go, types/cstorclusterplan.go, types/cstorclusterplan_test.go
This commit removes updating error information against status of CStorClusterConfig during reconciliation. This should remove hot loop path experienced due to constant updates to the status.
In addition, there are several unit tests against CStorClusterConfig reconciliation codebase.
=> fix(status): remove error updates against status

controller/cstorclusterconfig/reconciler.go, controller/cstorclusterconfig/reconciler_test.go, controller/cstorpoolcluster/reconciler.go
This commit fixes creating the desired CStorClusterPlan resource to make use of resulting fields than using observed CStorClusterConfig resource.
In addition, this commit removes updating status of CStorClusterPlan during reconciliation to avoid hot loop path.
=> fix(desired nodes): use resulting fields to build CStorClusterPlan

controller/blockdevice/reconciler.go, controller/cstorpoolcluster/reconciler.go
This commit sets resync to continue after 3 seconds if current reconciliation was skipped. A reconciliation may be skipped if one or more requirements are not met.
This should reduce the overall time to create a CStorPoolCluster.
=> fix(resync): reduce resync interval if reconcile is skipped

controller/blockdevice/reconciler.go, controller/cstorclusterconfig/reconciler.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, controller/cstorpoolcluster/reconciler_test.go, k8s/condition.go, k8s/iterator.go, k8s/iterator_test.go, k8s/util.go, types/cstorclusterconfig.go, util/string/string.go, util/string/string_test.go
This commit fixes the placement of raid groups in CSPC. Earlier logic used to result only in a single raidgroup for all RAID types. With this change, a mirror will have one or more raid groups with each
raid group having 2 block disks. Similarly raidz will have one or more raid groups with each raid group having 3 block disks.
There are additional improvements w.r.t utility functions for unstructured instances and string list.
closes https://github.com/mayadata-io/cstorpoolauto/issues/59
=> fix(raidgroups): fix placement of raid group in CStorPoolCluster

controller/cstorclusterconfig/reconciler.go, controller/cstorclusterconfig/reconciler_test.go, controller/cstorclusterplan/reconciler.go, controller/cstorclusterstorageset/reconciler.go, controller/cstorpoolcluster/reconciler.go, demo/basic/basic.yaml, types/cstorclusterconfig.go, types/cstorclusterstorageset.go, util/string/string.go
This commit fixes missing update to max pool count field in CStorClusterConfig. It has several Unit Tests that verifies this fix.
In addition, this commit introduces API changes to differentiate local devices from external ones. Here, external devices imply csi / cloud based disks. However, local devices imply those that are provisioned and attached to Kubernetes worker nodes. Local device(s) should be discoverable via NDM as BlockDevice(s).
closes https://github.com/mayadata-io/cstorpoolauto/issues/75
=> fix(maxpoolcount): fix updating max pool count

types/recommendation.go, types/recommendationrequest.go, types/reference.go
This PR adds 2 new schemas required to implement the Recommendation feature. 
[Design doc here](https://docs.google.com/document/d/1N78m0mTjEZ9iX4n73kcajpy13DqLpApzt8oBiJjO_6c)
This PR adds 2 new schemas required to implement the Recommendation feature.
```
1. CStorPoolClusterRecommendationRequest
2. CStorPoolClusterRecommendation
```
Schema for CStorPoolClusterRecommendationRequest
```go
import (
"k8s.io/apimachinery/pkg/api/resource"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
// CStorPoolClusterRecommendationRequest is a kubernetes custom
// resource that represents configuration input or requirement
// to create or scale one CStor pool.
type CStorPoolClusterRecommendationRequest struct {
metav1.TypeMeta   `json:",inline"`
metav1.ObjectMeta `json:"metadata"`
Spec …
```
=> feat(recommendation): add schema for CStorPoolcluster recommendation

controller/cstorclusterconfig/node.go, controller/cstorclusterconfig/node_test.go, controller/cstorclusterconfig/reconciler.go, types/cstorclusterplan.go, types/cstorclusterplan_test.go, unstruct/unstruct.go, unstruct/unstruct_test.go
This commits fixes node selection logic used to create CStorClusterPlan resource. Unit tests have been implemented to verify the same.
In addition, there are a few name changes done to unstruct package to make it more readable.
=> fix(node plan): fix node selection logic

controller/cstorclusterconfig/reconciler.go, controller/cstorclusterconfig/reconciler_test.go, demo/basic/cstor-operator.yaml, demo/basic/test.sh, deploy/config.yaml, deploy/operator.yaml, types/cstorclusterplan.go
This commit fixes the difference between observed and desired specification of CStorClusterPlan's spec.nodes field. This should avoid the cases where spec.nodes got nullified. Various unit tests have been added to verify the fix.
_NOTE: However, this test requires integration test or e2e test to verify & close the error._
=> fix(merge): fix diff between observed and desired nodes

config/metac.yaml, demo/basic/test.sh, deploy/config.yaml
This commit updates the names of metacontrollers to be short and precise. In addition, the deploy/config.yaml is made to be same as config/metac.yaml.
NOTE: deploy/config.yaml is used for testing purposes only.
NOTE: cstorpoolauto binary will always have the appropriate config file i.e. metac.yaml
=> chore(rename): update names of various metacontrollers

controller/cstorclusterconfig/node_test.go, unstruct/list.go, unstruct/selector.go, unstruct/selector_test.go, unstruct/unstruct.go, unstruct/unstruct_test.go
This commit makes use of metac's ResourceSelector to filter one or more unstructured instances. Selector can replace the conditions feature to filter unstructured instances.
NOTE: Controllers that makes use of Metac can benefit a lot from selector based matches of unstruct instances. This allows the code to filter specific instances than getting into nested branching logic.
=> feat(selector): introduce selector for unstruct instances

.github/workflows/build-image.yml
This PR adds GitHub action to run unit tests and build a docker image on every push.
=> feat(github-action): add github action to build image on every push

types/raidgroupconfig.go, types/raidgroupconfig_test.go, unstruct/util.go, util/blockdevice/util.go, util/blockdevice/util_test.go
This commit has following changes:
- 1/ fix utility function for block-device.
- bug: blockdevice spec.capacity.storage is a int64 type but logic reads it as a string
- fix: use int64 & subsequently convert it to resource.Quantity format.
- 2/ additional util functions for block-device and raid group config.
- 3/ new unit tests for all utility functions.
=> fix(capacity): fix capacity bug due to invalid datatype parsing

unstruct/util.go, util/blockdevice/topology.go, util/blockdevice/util.go, util/blockdevice/util_test.go
Rename utility functions in bdutil package to avoid confusion
- function name ends with error will return error if there is an error or value is empty or not matching.
- function name not ends with error will return error if there is an error.
=> rename(bdutil): rename utility functions in bdutil package

pkg/recommendation/capacity.go, pkg/recommendation/device.go, pkg/recommendation/device_test.go, types/recommendationrequest.go, util/blockdevice/topology.go
This PR adds support to get device recommendations for given configurations.
This adds a logic to recommend blockdevices for creating a cstor pool. It accepts the parameters for recommendation like poolCapacity which is the requested pool capacity and raidConfig which is the requested raid type (stripe, mirror, raidz, raidz2) for creating cStor pool. It also requires list of blockdevices as an input. It returns the recommended blockdevices in each node for each device type (HDD, SSD, etc).
Client code: 
```
raidconfig := &types.RaidGroupConfig{
Type:             types.PoolRAIDType("mirror"),
GroupDeviceCount: 2,
}
if err := raidconfig.PopulateDefaultGroupDeviceCountIfNotPresent(); err != nil {
raidconfig = types.GetDefaultRaidGroupConfig()
}
if err := raidconfig.Validate(); err != nil { …
```
=> feat(recommendation): add device based recommendation for given configuration

cmd/main.go, controller/cstorpoolcluster/reconciler.go, controller/localdevice/reconciler.go, controller/localdevice/reconciler_test.go, types/cstorclusterconfig.go, unstruct/iterator.go, unstruct/iterator_test.go, unstruct/list.go, unstruct/list_test.go, unstruct/selector_test.go, util/blockdevice/helper.go, util/blockdevice/helper_test.go, util/blockdevice/list_helper.go, util/blockdevice/list_helper_test.go, util/cstorclusterconfig/helper.go, util/cstorclusterconfig/helper_test.go, util/cstorpoolcluster/builder.go, util/cstorpoolcluster/builder_test.go, util/cstorpoolcluster/helper.go, util/cstorpoolcluster/helper_test.go, util/metac/validation.go, util/metac/validation_test.go, util/string/string.go, util/string/string_test.go
This commit adds logic to consider block devices that are already discovered in one or more worker nodes. This logic considers these block devices based on the labels assigned to these devices. They are then used to form a CStorPoolCluster resource in Kubernetes.
In addition, there are several bug fixes done due to extensive implementation of unit tests across several packages.
=> feat(local): add local disk based cstor pool auto provisioning

pkg/recommendation/device.go, pkg/recommendation/device_test.go, types/raidgroupconfig.go, types/raidgroupconfig_test.go
- Change the name of raidType from 'type' to 'raidType' in structure.
- Update the device recommendation logic. It was not returning the prevDataDevices if the requestedCapacity is equal to the capacity.
=> fix(recommendation): fix the device recommendation logic and update the recommendation structure

cmd/main.go, config/metac.yaml, controller/localdevice/finalizer.go, controller/localdevice/finalizer_test.go, controller/localdevice/reconciler.go, go.mod
This commit implements the finalize logic against `CStorClusterConfig` objects. This is particular to those `CStorClusterConfig` instances that has local device selectors.
_NOTE: finalize is opposite of sync logic_
_NOTE: finalize is triggered only when watch object is deleted whereas sync logic is triggered only when watch object is created or updated or after some time interval_
closes #109
=> feat(localdevice): delete CStorPoolCluster when CStorClusterConfig is deleted

util/blockdevice/topology.go
avoid mix block size recommendation
Earlier implementation -
```
If system has HDD of 4k and 16k then it gives 3 recommendations -
HDD-4k -> This recommendation contains block devices of block size 4k.
HDD-16k -> This recommendation contains block devices of block size 16k.
HD -> This recommendation contains block devices of both block size 4k and 16k.
```
New implementation -
```
If system has HDD of 4k and 16k then it gives 3 recommendations -
HDD-4k -> This recommendation contains block devices of block size 4k.
HDD-16k -> This recommendation contains block devices of block size 16k.
```
=> fix(recommendation): avoid mix block size recommendation

common/cstorpoolcluster/builder.go, common/cstorpoolcluster/builder_test.go, common/cstorpoolcluster/helper.go, common/cstorpoolcluster/helper_test.go, config/localdevice/metac.yaml, controller/localdevice/finalizer_test.go, controller/localdevice/reconciler_test.go, types/gvk.go
This commit has following changes:
- `poolConfig.defaultRaidGroupType` renamed to `poolConfig.dataRaidGroupType` 
- `poolConfig.overProvisioning` renamed to `poolConfig.thickProvision`
```yaml
poolConfig:
compression: off
dataRaidGroupType: stripe
thickProvision: false
```
- `v1` API splits `raidGroups` of `v1alpha1` to `dataRaidGroups` & `writeCacheGroups`
```yaml
spec:
pools:
- nodeSelector:
kubernetes.io/hostname: noded-1
dataRaidGroups:
-  blockDevices:
- blockDeviceName: blockdevice-1-node-1
```
- Stripe is now built as a single raid group of n devices instead of earlier strategy to build n groups each having 1 disk.
=> feat(local): add support for v1 cspc creation

common/blockdevice/util.go, common/blockdevice/util_test.go, go.sum
Filter reserved block devices from CStor Pool recommendation. Reserved block devices will have `openebs.io/block-device-tag` label.
=> (recommendation): don't list reserved block devices
